# Generated by Django 4.1.3 on 2022-11-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField()),
                ('deleted_at', models.DateTimeField()),
                ('deleted_by', models.IntegerField()),
                ('is_active', models.IntegerField(default=1)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('tenant_id', models.IntegerField()),
            ],
            options={
                'db_table': 'container_type',
            },
        ),
        migrations.AddConstraint(
            model_name='containertype',
            constraint=models.UniqueConstraint(fields=('name', 'tenant_id', 'is_active'), name='name__tenant_id__uq'),
        ),
    ]
