# Generated by Django 4.1.3 on 2022-11-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
