# Generated by Django 4.1.3 on 2022-11-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_type', '0003_alter_containertype_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertype',
            name='deleted_by',
            field=models.IntegerField(null=True),
        ),
    ]
