# Generated by Django 4.1.3 on 2022-11-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_type', '0005_alter_containertype_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertype',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
