# Generated by Django 4.1.3 on 2022-11-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_type', '0007_alter_containertype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertype',
            name='is_active',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
